# Generated by Django 5.2.6 on 2025-09-18 00:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=Decimal('1000000000.00'), max_digits=15)),
                ('fecha_inicio', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=6)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='portfolio.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='portfolio.portafolio')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PesoPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_inicial', models.DecimalField(decimal_places=6, max_digits=8)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_portafolio', to='portfolio.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='portfolio.portafolio')),
            ],
            options={
                'unique_together': {('portafolio', 'activo')},
            },
        ),
        migrations.CreateModel(
            name='PesoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=6, max_digits=8)),
                ('valor_activo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_dinamicos', to='portfolio.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_dinamicos', to='portfolio.portafolio')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('portafolio', 'activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='CantidadActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades_portafolio', to='portfolio.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='portfolio.portafolio')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('portafolio', 'activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='portfolio.activo')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('activo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ValorPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='portfolio.portafolio')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('portafolio', 'fecha')},
            },
        ),
    ]
